language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
    - php: 7.2
      env: XDEBUG_OFF="yes"

before_script:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

script:
  - make
  - make test-all

after_success:
  - make coveralls
  - bash <(curl -s https://codecov.io/bash)
