#
# JBZoo Toolbox - Utils
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Utils
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Utils
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
  schedule:
    - cron: '50 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      JBZOO_COMPOSER_UPDATE_FLAGS: ${{ matrix.composer_flags }}
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4, 8.0 ]
        experimental: [ false ]
        coverage: [ xdebug, none ]
        composer_flags: [ "--prefer-lowest", "" ]
        include:
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.coverage }}
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make update --no-print-directory

      - name: üß™ PHPUnit Tests
        continue-on-error: ${{ matrix.experimental }}
        run: make test --no-print-directory

      - name: Uploading coverage to coveralls
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make report-coveralls --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit - ${{ matrix.php-version }} - ${{ matrix.coverage }}
          path: build/


  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: üëç Code Quality
        run: make codestyle --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linters - ${{ matrix.php-version }}
          path: build/


  report:
    name: Reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4, 8.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make update --no-print-directory

      - name: üìù Build Reports
        continue-on-error: ${{ matrix.experimental }}
        run: make report-all --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports - ${{ matrix.php-version }}
          path: build/
